services:
  postgres:
    image: postgres:16-alpine
    container_name: amacor-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: amacor
      POSTGRES_PASSWORD: amacor123
      POSTGRES_DB: amacor
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
